comment lines

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,8 +13,8 @@ jobs:
         run: echo "Hello, CI/CD!"
 
         # uncommented
-      - name: Simulate an error
-        run: echo "About to fail" ; exit 1
+      #- name: Simulate an error
+      #  run: echo "About to fail" ; exit 1
 
       - name: Another greeting
         run: echo "Hello, CI/CD again!"
